### ISSUE TITLE
💌📯 Updates

### ISSUE THREAD

**Issue by deerboy** [deerboy/rest.js#17]
If you are interested on updates, you can subscribe to this issue. I'll post weekly-ish comments with project updates. 

<a name="next-steps"></a>
## Next steps / Progress

We will keep releasing the package as `github` on npm for foreseeable time, before we eventually deprecate it and release `octokit` instead. We will give you an advanced notice and prepare a migration guide. We will also keep maintaining `github` for some time and release bug/security fixes, but will no longer add new features.

<a name="maintainability"></a>
### ✅  Maintainability 

<details>
  <summary>
    Released as  <a href="https://github.com/octokit/node-github/releases/tag/v13.0.0">v13.0.0</a>
  </summary>
In order to quickly accept contributions, we have to trust our test setup. Once a contribution is merged, the release should happen immediately to retain contributors

- [x] **Tests**. I’ve started implementing tests based on [our examples](https://github.com/octokit/node-github/tree/master/examples). We created a separate [Octokit Fixtures](https://github.com/octokit/fixtures) project which detects changes to the GitHub API using a daily cron job on travis. You can see the current status at  https://github.com/octokit/fixtures/issues/14, I’d love to take the opportunity to onboard new contributors, just [comment on the issue](https://github.com/octokit/fixtures/issues/14) if you are interested.
- [x] **Linting.** Thanks @Zeke! (https://github.com/octokit/node-github/pull/600)
- [x] #621 **Test coverage**. The goal is 💯
- [x] **Automate releases and dependency updates**. Using [semantic-release](https://github.com/semantic-release/semantic-release) & [Greenkeeper](https://greenkeeper.io/). Done via [#617](https://github.com/octokit/node-github/pull/617) & [#618](https://github.com/octokit/node-github/pull/618)
- [x] **Drop support for unmaintained Node versions**. We already just test Node 4, 6 and 8 on Travis. Done via [v12.0.0](https://github.com/octokit/node-github/releases/tag/v12.0.0)

  With minimal support of Node 4, we can
  - [x] #622 remove custom Promise handling
  - [x] #630 use Object.assign instead of a custom extend method
  
- [x] #666 **automate API DOCS generation** at http://octokit.github.io/node-github/
</details>

<a name="browser-support"></a>
### ✅ Browser support
<details>
  <summary>
    Released as  <a href="https://github.com/octokit/node-github/releases/tag/v15.0.0">v15.0.0</a>
  </summary>
The current library cannot be used in the browser. With browser support, bundling size becomes a critical metric, so we will explore modularization and and other ways to reduce the bundle size for usage in browser and other more constraint environments

- [x] #635 Compatibility with browserify / webpack
  - [x] #633 remove built-in netrc support
  - [x] #637 move definitions out of routes.json
- [x] Add bundle size monitoring / thresholds to CI https://github.com/gr2m/octokit-rest-browser-experimental/pull/11
- [ ] Automate built files / CDN releases
</details>

<a name="v16"></a>

### ✅  Revise APIs 

<details>
  <summary>
    Released as  <a href="https://github.com/octokit/node-github/releases/tag/v16.0.0">v16.0.0</a>
  </summary>

As the official JavaScript SDK for GitHub’s REST API, we want to align it very closely to the [REST API documentation](https://developer.github.com/v3/). Every endpoint will have its own method, the parameters will have the same names and the method method names will be derived from the endpoint section titles of the REST API. These will be kept up to date continuously using automated scripts (see [octokit/routes](https://github.com/octokit/routes)). If parameters or names need to be changed, we will deprecated them in order to keep the need to release breaking versions to an absolute minimum.

After v16.0.0, new APIs and features (such as better support for preview headers, enterprise versions, etc) will automatically be added as we add support for it in [octokit/routes](https://github.com/octokit/routes). We will deprecate methods / parameters as needed and release breaking versions aligned with GitHub’s Enterprise versions, in which we will remove all deprecated APIs, so updating should be fairly simple.
</details>

<a name="v17"></a>
### 🚧 octokit.js ([v17.0.0](https://github.com/octokit/rest.js/milestone/4))

After v16.0.0, we will focus on [octokit.js](https://github.com/octokit/octokit.js) – the all batteries included client for the GitHub platform.

- [x] Define API: https://github.com/octokit/octokit.js
- [ ] Complete support 
  - [x] [v3 REST API](https://developer.github.com/v3/)
  - [x] [v4 GraphQL API](https://developer.github.com/v4/)
  - [x] [Webhooks](https://developer.github.com/webhooks/)
  - [ ] [Oauth Apps](https://developer.github.com/apps/building-oauth-apps/)
  - [x] [GitHub Apps](https://developer.github.com/apps/)
  - [ ] [Actions](https://developer.github.com/actions/)
  - [ ] Make all aspects work together nicely
- [x] Modular architecture (see [plugins/](https://github.com/octokit/rest.js/tree/master/plugins))
- [x] Implement best practises (see https://github.com/octokit/plugin-throttling.js, https://github.com/octokit/plugin-retry.js)
- [x] `octokit` will implement [best practises](https://developer.github.com/v3/guides/best-practices-for-integrators/) such as throttling requests.
- [ ] Turn `@octokit/rest` into a plugin, or make it usable as a plugin
- [ ] Publish octokit v1.0.0

See also: https://github.com/octokit/octokit.js

## About myself 👋

Hello there, I’m Gregor! If you run into any trouble as user, contributor or fellow maintainer, I’ll do my very best to help you out :)

I’m maintaining a few other JavaScript/Node projects like [nock](https://github.com/node-nock), [semantic-release](https://github.com/semantic-release) and [Hoodie](https://github.com/hoodiehq). I’m passionate about [welcoming and inclusive communities](http://hood.ie/blog/welcoming-communities) and see it as main responsibility to encourage and support contributions of all kind. You can follow me on Twitter: [@gr2m](https://twitter.com/gr2m)
